# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumari',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
